services:
  - type: web
    name: ozone-predictor
    env: python
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: VITE_API_URL
        value: "" 
